### ISSUE TITLE
Uncaught AssertionError


### ISSUE THREAD

**Issue by saberraz** [wonder-sk/CadNodeTool#14]
Steps to reproduce
1. First 
2. Second 
3. Third 

```
Traceback (most recent call last):
  File "C:/Users/saber/.qgis2/python/plugins\CadNodeTool\nodetool.py", line 272, in cadCanvasMoveEvent
    self.mouse_move_not_dragging(e)
  File "C:/Users/saber/.qgis2/python/plugins\CadNodeTool\nodetool.py", line 407, in mouse_move_not_dragging
    is_circular_vertex = _is_circular_vertex(geom, m.vertexIndex())
  File "C:/Users/saber/.qgis2/python/plugins\CadNodeTool\nodetool.py", line 62, in _is_circular_vertex
    assert isinstance(g, QgsCurveV2)
AssertionError

```

CadNodeTool 1.0, QGIS 2.14.5-Essen on Windows 7

**Comment by wonder-sk** [comment]
When does that happen?

**Comment by saberraz** [comment]
When working with polygons.
