### ISSUE TITLE
Problem with split tools and generated node

### ISSUE THREAD

**Issue by saberraz** [wonder-sk/CadNodeTool#18]
Steps to reproduce
1. Use the Split multi-parts tool to split a line
2. Try to move the generated node
3. Crash

```
Traceback (most recent call last):
  File "C:/Users/saber/.qgis2/python/plugins\CadNodeTool\nodetool.py", line 272, in cadCanvasMoveEvent
    self.mouse_move_not_dragging(e)
  File "C:/Users/saber/.qgis2/python/plugins\CadNodeTool\nodetool.py", line 412, in mouse_move_not_dragging
    if self.is_match_at_endpoint(m):
  File "C:/Users/saber/.qgis2/python/plugins\CadNodeTool\nodetool.py", line 359, in is_match_at_endpoint
    polyline = _geometry_to_polyline(geom)  # TODO: does not work with multi-type
  File "C:/Users/saber/.qgis2/python/plugins\CadNodeTool\nodetool.py", line 75, in _geometry_to_polyline
    assert isinstance(g, QgsCurveV2)
AssertionError

```

CadNodeTool 1.0, QGIS 2.14.5-Essen on Windows 7

**Comment by saberraz** [comment]
![split_node](https://cloud.githubusercontent.com/assets/2649047/18049201/a6a59e90-6dde-11e6-82e2-9b85d250b56a.gif)
